"""Add user relationship to Reservation

Revision ID: 203571a010cc
Revises: 1f6926b05dcb
Create Date: 2023-08-08 13:49:15.269152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203571a010cc'
down_revision = '1f6926b05dcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        # В этой строке вместо None укажите название внешнего ключа.
        batch_op.create_foreign_key(
            'fk_reservation_user_id_user', 'user', ['user_id'], ['id']
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        # В этой строке вместо None укажите название внешнего ключа.
        batch_op.drop_constraint(
            'fk_reservation_user_id_user', type_='foreignkey'
            )
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
